# Generated by Django 2.2.5 on 2019-11-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_the_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='the_class',
        ),
    ]
