# Generated by Django 2.2.5 on 2019-11-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jun_school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название предмета:', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='theclass',
            name='subject',
            field=models.ManyToManyField(help_text='Выберите предметы для класса:', to='jun_school.Subject'),
        ),
    ]
