# Generated by Django 2.2.5 on 2019-11-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jun_school', '0002_auto_20191109_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'кпредмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='theclass',
            options={'verbose_name': 'клас', 'verbose_name_plural': 'Классы'},
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jun_school.TheClass')),
            ],
            options={
                'verbose_name_plural': 'Ученики',
                'verbose_name': 'ученика',
            },
        ),
    ]
