# Generated by Django 2.2.5 on 2019-11-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jun_school', '0003_auto_20191109_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
