# Generated by Django 2.2.5 on 2019-11-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jun_school', '0005_theclass_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Введите название предмета:', max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='theclass',
            name='name',
            field=models.CharField(max_length=5, verbose_name='Наименование'),
        ),
    ]
