# Generated by Django 2.2.5 on 2019-11-10 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jun_school', '0006_auto_20191109_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theclass',
            name='student',
            field=models.ManyToManyField(help_text='Выберите ученика:', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='theclass',
            name='subject',
            field=models.ManyToManyField(help_text='Выберите предметы для класса:', to='jun_school.Subject', verbose_name='Предмет'),
        ),
    ]
