# Generated by Django 2.2.5 on 2019-11-12 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jun_school', '0007_auto_20191110_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='JunStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('the_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jun_school.TheClass')),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
