# Generated by Django 2.2.5 on 2019-11-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jun_school', '0008_junstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theclass',
            name='student',
        ),
    ]
