# Generated by Django 2.2.5 on 2019-11-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jun_school', '0009_remove_theclass_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junstudent',
            name='the_class',
        ),
        migrations.AddField(
            model_name='junstudent',
            name='the_class',
            field=models.ManyToManyField(to='jun_school.TheClass'),
        ),
    ]
