# Generated by Django 2.2.5 on 2019-11-12 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jun_school', '0010_auto_20191112_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junstudent',
            name='student',
        ),
        migrations.AddField(
            model_name='junstudent',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='junstudent',
            name='the_class',
        ),
        migrations.AddField(
            model_name='junstudent',
            name='the_class',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jun_school.TheClass'),
        ),
    ]
