# Generated by Django 2.2.5 on 2019-11-12 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jun_school', '0012_auto_20191112_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junstudent',
            name='the_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jun_school.TheClass'),
        ),
    ]
