# Generated by Django 2.2.5 on 2019-11-12 22:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jun_school', '0013_auto_20191112_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JunStudent',
            new_name='Student',
        ),
    ]
